name: software
description: An Ubuntu software app made with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.1.2
  image: ^3.1.3
  provider: ^6.0.2
  safe_change_notifier: ^0.1.0+1
  snapd: ^0.1.1
  yaru: ^0.3.2
  yaru_icons:
    git: https://github.com/ubuntu/yaru_icons.dart
  yaru_widgets: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
