name: software
description: An Ubuntu software app made with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaru: ^0.3.1
  yaru_icons: ^0.2.1
  yaru_widgets:
    git: https://github.com/ubuntu/yaru_widgets.dart
  snapd: ^0.1.1
  provider: ^6.0.2
  handy_window: ^0.1.2
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true